baseURL = '/'
languageCode = 'en-us'
title = '4strodev'
paginate = 5

[params]
	contentTypeName = "posts"
	defaultTheme = "dark"
	showMenuItems = 2
	showReadingTime = false

[languages]
	[languages.en]
    title = "4strodev"
    subtitle = "A web made for a geek for geeks"
    keywords = "4strodev programming web backend"
    copyright = "4strodev"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "4strodev"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "me"
        name = "Me"
        url = "/pages/me"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/pages/about"

[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-hello-friend -> themes/hello-friend"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-hello-friend'
