baseURL = ''
languageCode = 'en-us'
title = '4strodev'
theme = ["github.com/Mitrichius/hugo-theme-anubis"]
disqusShortname = "asd;likfaj"

[[menu.main]]
identifier = 'archive'
name = 'Archive'
title = 'Archive'
url = '/posts/'
weight = 1

[[menu.main]]
identifier = 'tags'
name = 'Tags'
title = 'Tags'
url = '/tags/'
weight = 2

[[menu.main]]
identifier = 'about'
name = 'About'
title = 'About'
url = '/pages/about/'
weight = 3

[[menu.main]]
identifier = 'about-me'
name = 'About Me'
title = 'About Me'
url = '/pages/me/'
weight = 4


[params]
style = 'auto'
dateFormat = "2006-01-02"
paginationSinglePost = true
readMore = true
author = "4strodev"
description = "A description"

[markup.goldmark.renderer]
unsafe = true

